displayName=420 kc
author=420 kc
support=https://github.com/420kc/420kcp/issues
description=Celebrate 420 kill count milestones with chat messages
tags=420,kc,boss,kill count
plugins=com.fourtwentykc.FourTwentyKcPlugin
