displayName=420 kc
author=420 kc
support=https://github.com/420kc/420kcp/issues
description=Celebrate when boss, activity, or clue counts reach 420
tags=420,kc,boss,kill count,kill clog,activity,clue,clue scroll
plugins=com.fourtwentykc.FourTwentyKcPlugin
build=standard
version=1.1.2
